// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace BTLNhom3.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    partial class MvcMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BTLNhom3.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("BTLNhom3.Models.Login", b =>
                {
                    b.Property<string>("IdUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("BTLNhom3.Models.Quanlydonhang", b =>
                {
                    b.Property<string>("Madonhang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Makhachhang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Masanpham")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngaylamnv")
                        .HasColumnType("TEXT");

                    b.HasKey("Madonhang");

                    b.HasIndex("Makhachhang");

                    b.HasIndex("Masanpham");

                    b.ToTable("Quanlydonhang");
                });

            modelBuilder.Entity("BTLNhom3.Models.Quanlykhachhang", b =>
                {
                    b.Property<string>("Makhachhang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sodienthoai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tenkhachhang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Makhachhang");

                    b.ToTable("Quanlykhachhang");
                });

            modelBuilder.Entity("BTLNhom3.Models.Quanlyncc", b =>
                {
                    b.Property<string>("Mancc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenncc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("diachi")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<int>("sodienthoai")
                        .HasColumnType("INTEGER");

                    b.HasKey("Mancc");

                    b.ToTable("Quanlyncc");
                });

            modelBuilder.Entity("BTLNhom3.Models.Quanlysanpham", b =>
                {
                    b.Property<string>("Masanpham")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tensanpham")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("giatien")
                        .HasColumnType("TEXT");

                    b.Property<string>("mausac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("soluong")
                        .HasColumnType("INTEGER");

                    b.HasKey("Masanpham");

                    b.ToTable("Quanlysanpham");
                });

            modelBuilder.Entity("BTLNhom3.Models.Quanlydonhang", b =>
                {
                    b.HasOne("BTLNhom3.Models.Quanlykhachhang", "Quanlykhachhang")
                        .WithMany()
                        .HasForeignKey("Makhachhang");

                    b.HasOne("BTLNhom3.Models.Quanlysanpham", "Quanlysanpham")
                        .WithMany()
                        .HasForeignKey("Masanpham");

                    b.Navigation("Quanlykhachhang");

                    b.Navigation("Quanlysanpham");
                });
#pragma warning restore 612, 618
        }
    }
}
