// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcMovie.Data;

#nullable disable

namespace BTLNhom3.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    partial class MvcMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BTLNhom3.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassWord")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("BTLNhom3.Models.Quanlysanpham", b =>
                {
                    b.Property<string>("Masanpham")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tensanpham")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("giatien")
                        .HasColumnType("TEXT");

                    b.Property<string>("mausac")
                        .HasColumnType("TEXT");

                    b.Property<int>("size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("soluong")
                        .HasColumnType("INTEGER");

                    b.HasKey("Masanpham");

                    b.ToTable("Quanlysanpham");
                });
#pragma warning restore 612, 618
        }
    }
}
